### ISSUE TITLE
Sometimes setting session data fails

### ISSUE THREAD

**Issue by ile** [derbyjs/racer#194]
Summary: Express and racer-browserchannel have some trouble with each other because of a "race condition" with `res.end()`.
- I set some session data with `req.flash()` (or with anything probably)
- and call `res.redirect()` (this makes express call `res.end()` I think)
- -> Sometimes the data I wrote have been cleared after redirect is done (when browser shows the new url). Session data should be there and not cleared.

I added `console.trace()` in express\node_modules\connect\node_modules\express-session\session\session.js:

``` javascript
Session.prototype.save = function(fn){
  console.trace('session.save', new Date().toISOString(), this)
  this.req.sessionStore.set(this.id, this, fn || function(){});
  return this;
};
```

This show the following:

```
setting flash.error ... and calling redirect after that ...

Trace: session.save 2014-10-18T00:11:32.640Z { cookie:
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  passport: {},
  userId: '236d8b9d-dd1d-4fe3-8dee-307575d19fdd',
  flash:
   { error: [ 'Some errors...' ] } }
  at Session.save (/data/myapp/node_modules/express/node_modules/connect/node_modules/express-session/session/session.js:72:11)
  at Session.save (/data/myapp/node_modules/express/node_modules/connect/node_modules/express-session/index.js:293:15)
  at ServerResponse.end (/data/myapp/node_modules/express/node_modules/connect/node_modules/express-session/index.js:264:21)
  at ServerResponse.res.redirect (/data/myapp/node_modules/express/lib/response.js:769:8)
  at /data/myapp/node_modules/d-passport/lib/middleware.js:327:18
  at callbacks (/data/myapp/node_modules/express/lib/router/index.js:164:37)
  at param (/data/myapp/node_modules/express/lib/router/index.js:138:11)
  at pass (/data/myapp/node_modules/express/lib/router/index.js:145:5)
  at Router._dispatch (/data/myapp/node_modules/express/lib/router/index.js:173:5)
  at Object.handle (/data/myapp/node_modules/d-passport/lib/middleware.js:85:19)
  at next (/data/myapp/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at Object.handle (/data/myapp/node_modules/d-passport/lib/middleware.js:81:14)
  at next (/data/myapp/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at SessionStrategy.strategy.pass (/data/myapp/node_modules/d-passport/node_modules/passport/lib/middleware/authenticate.js:318:9)
  at SessionStrategy.authenticate (/data/myapp/node_modules/d-passport/node_modules/passport/lib/strategies/session.js:67:10)
  at attempt (/data/myapp/node_modules/d-passport/node_modules/passport/lib/middleware/authenticate.js:341:16)
  at Object.authenticate [as handle] (/data/myapp/node_modules/d-passport/node_modules/passport/lib/middleware/authenticate.js:342:7)
  at next (/data/myapp/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at Object.initialize [as handle] (/data/myapp/node_modules/d-passport/node_modules/passport/lib/middleware/initialize.js:62:5)
  at next (/data/myapp/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at Object.handle (/data/myapp/node_modules/d-passport/node_modules/connect-flash/lib/flash.js:21:5)
  at next (/data/myapp/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at methodOverride (/data/myapp/node_modules/express/node_modules/connect/node_modules/method-override/index.js:77:5)
  at /data/myapp/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:41:7
  at methodOverride (/data/myapp/node_modules/express/node_modules/connect/node_modules/method-override/index.js:77:5)
  at Object.handle (/data/myapp/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:39:5)
  at next (/data/myapp/node_modules/express/node_modules/connect/lib/proto.js:169:15)
  at multipart (/data/myapp/node_modules/express/node_modules/connect/lib/middleware/multipart.js:89:27)
  at /data/myapp/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:64:9
  at /data/myapp/node_modules/express/node_modules/connect/node_modules/body-parser/lib/read.js:100:5
  at IncomingMessage.onEnd (/data/myapp/node_modules/express/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
  at IncomingMessage.g (events.js:180:16)
  at IncomingMessage.emit (events.js:92:17)
  at _stream_readable.js:943:16
  at process._tickCallback (node.js:419:13)

Trace: session.save 2014-10-18T00:11:32.727Z { cookie:
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  passport: {},
  userId: '236d8b9d-dd1d-4fe3-8dee-307575d19fdd',
  flash: {} }
  at Session.save (/data/myapp/node_modules/express/node_modules/connect/node_modules/express-session/session/session.js:72:11)
  at Session.save (/data/myapp/node_modules/express/node_modules/connect/node_modules/express-session/index.js:293:15)
  at ServerResponse.end (/data/myapp/node_modules/express/node_modules/connect/node_modules/express-session/index.js:264:21)
  at end (/data/myapp/node_modules/racer-browserchannel/node_modules/browserchannel/dist/server.js:99:20)
  at [object Object]._onTimeout (/data/myapp/node_modules/racer-browserchannel/node_modules/browserchannel/dist/server.js:618:18)
  at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

Trace: session.save 2014-10-18T00:11:33.101Z { cookie:
   { path: '/',
     _expires: null,
     originalMaxAge: null,
     httpOnly: true },
  passport: {},
  userId: '236d8b9d-dd1d-4fe3-8dee-307575d19fdd',
  flash: {} }
  at Session.save (/data/myapp/node_modules/express/node_modules/connect/node_modules/express-session/session/session.js:72:11)
  at Session.save (/data/myapp/node_modules/express/node_modules/connect/node_modules/express-session/index.js:293:15)
  at ServerResponse.end (/data/myapp/node_modules/express/node_modules/connect/node_modules/express-session/index.js:264:21)
  at Object.end (/data/myapp/node_modules/racer-browserchannel/node_modules/browserchannel/dist/server.js:99:20)
  at [object Object].BCSession._clearBackChannel (/data/myapp/node_modules/racer-browserchannel/node_modules/browserchannel/dist/server.js:315:29)
  at [object Object].BCSession._flush (/data/myapp/node_modules/racer-browserchannel/node_modules/browserchannel/dist/server.js:496:12)
  at /data/myapp/node_modules/racer-browserchannel/node_modules/browserchannel/dist/server.js:459:20
  at process._tickCallback (node.js:419:13)

** NEW URL HERE, SESSION DATA GONE **
```

What we see here, is that browserchannel calls `res.end()` twice after I have called my `res.redirect()`... Browserchannel's `res.end()` is here: /data/myapp/node_modules/racer-browserchannel/node_modules/browserchannel/dist/server.js:99:20

After that the redirect actually takes place, but it's a bit too late, because browserchannel's `res.end()` makes the session data overwritten.

There are probably more serious cases that just flash data. For example, "logout" didn't seems to always work, i.e. I destroyed the session but in the end it wasn't gone. This may be part of this problem (haven't checked though).

Not sure where the problem really is - there is this timer at `/data/myapp/node_modules/racer-browserchannel/node_modules/browserchannel/dist/server.js:618` ... maybe there?

**Comment by robin-chilliapple** [comment]
I am also facing the same problem. Did anyone found a solution for this?

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
