### ISSUE TITLE
Error on alpha 35

### ISSUE THREAD

**Issue by xscheiner** [derbyjs/racer#218]
Hi:

I did a new install today on my test and I am getting this in my log over and over:

```
TypeError: Cannot call method 'slice' of undefined
249     at Doc.RemoteDoc._onOp (/srv/sites/editor/node_modules/derby/node_modules/racer/lib/Model/RemoteDoc.js:413:26)
250     at null.<anonymous> (/srv/sites/editor/node_modules/derby/node_modules/racer/lib/Model/RemoteDoc.js:30:9)
251     at MicroEvent.emit (/srv/sites/editor/node_modules/derby/node_modules/racer/node_modules/share/lib/client/microevent.js:54:20)
252     at /srv/sites/editor/node_modules/derby/node_modules/racer/node_modules/share/lib/client/doc.js:668:15
253     at Object.json.incrementalApply (/srv/sites/editor/node_modules/derby/node_modules/racer/node_modules/share/node_modules/ottypes/lib/json0.js:247:5)
254     at Doc._otApply (/srv/sites/editor/node_modules/derby/node_modules/racer/node_modules/share/lib/client/doc.js:666:12)
255     at Doc._onMessage (/srv/sites/editor/node_modules/derby/node_modules/racer/node_modules/share/lib/client/doc.js:400:12)
256     at Connection.handleMessage (/srv/sites/editor/node_modules/derby/node_modules/racer/node_modules/share/lib/client/connection.js:220:20)
257     at StreamSocket.socket.onmessage (/srv/sites/editor/node_modules/derby/node_modules/racer/node_modules/share/lib/client/connection.js:128:18)
258     at StreamSocket.Channel.socket.onmessage (/srv/sites/editor/node_modules/derby/node_modules/racer/lib/Channel.js:19:28)
```

When I force back to alpha 27, which was what I had before, the problem goes away.

**Comment by craigbeck** [comment]
Thanks for your contributing your issue.

We have recently been actively updating the [Derby](https://github.com/derbyjs/derby/releases) and [Racer](https://github.com/derbyjs/racer/releases) packages, and both repos are now in Typescript and published with types on npm. As we have quite a few old issues open we have made the decision to close out of date issues. 

If this issue still matters to you we encourage reproducing against the current versions of the repo and opening a new issue.
